#spring:
#  application:
#    name: sunmall-coupon
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#      config:
#        server-addr: 127.0.0.1:8848
#        namespace: llcb4acdbf-af5b-442d-8869-6116b367416a
#        extension-configs:
#          - dataId: coupon.yaml
#            group: dev
#            refresh: true
#server:
#  port: 8080